### ISSUE TITLE
Wiring for buttons

### ISSUE THREAD

**Issue by mikkelvp** [uncodead/BrewUNO#50]
Could you please provide a diagram or description on how to wire buttons?

**Comment by dumpamob** [comment]
Done. Simple wiring diagram updated.

**Comment by mikkelvp** [comment]
Thanks!

**Comment by mikkelvp** [comment]
![IMG_20200505_202209](https://user-images.githubusercontent.com/9072378/81114767-f2991480-8f22-11ea-87e6-942e8f25346e.jpg)
@dumpamob My LCD gets no data when going through the PCF8574. Works without PCF8574.
Am i missing something or is the PCF8574 maybe faulty?

**Comment by dumpamob** [comment]
The BrewUNO display was developed on a 20x4 LCD, it is recommended to use it. Possibly your problem is the address of PCF8574. In the "src" folder, open the Lcd.h file, line 12, change the 0x20 to 0x38 and upload the firmware again. Another way to find out what the PCF8574 addresses are is by loading an i2C scanner file.

**Comment by mikkelvp** [comment]
@dumpamob 0x38 was the correct address, thanks! 
Can't get my buttons working though. I'm using these ![_AC_SL1500_](https://images-na.ssl-images-amazon.com/images/I/61zIT4OiTJL._AC_SL1500_.jpg)
Any suggestions?
